### ISSUE TITLE
Netlify CLI 2.48 is breaking dev environment

### ISSUE THREAD

**Issue by chiubaca** [chiubaca/vue-netlify-fauna-starter-kit#33]
Issues appears to be related to https://github.com/netlify/cli/issues/850 
`npm start` is failing with

```
Error: "port" and "targetPort" options cannot have same values. Please consult the documentation for more details: https://cli.netlify.com/netlify-dev#netlifytoml-dev-block
    at module.exports.serverSettings (C:/Users/alexc/AppData/Roaming/npm/node_modules/netlify-cli/src/utils/detect-server.js:108:13)
    at DevCommand.run (C:/Users/alexc/AppData/Roaming/npm/node_modules/netlify-cli/src/commands/dev/index.js:413:26)    at async DevCommand._run (C:/Users/alexc/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (C:/Users/alexc/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (C:/Users/alexc/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (C:/Users/alexc/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-vue-netlify-auth@0.1.0 start: `netlify dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-vue-netlify-auth@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alexc\AppData\Roaming\npm-cache\_logs\2020-05-02T14_12_46_890Z-debug.log
```

**Comment by chiubaca** [comment]
work around -  `npm install netlify-cli@2.45 -g`
