### ISSUE TITLE
dest.end is not a function

### ISSUE THREAD

**Issue by paulrosen** [chiubaca/vue-netlify-fauna-starter-kit#42]
Hi, I'm trying to run this demo locally but getting this error:
```
$ npm start           
Recreating fauna-starter ... done
Attaching to fauna-starter
fauna-starter | 
fauna-starter | > simple-vue-netlify-auth@0.1.0 start /srv/app
fauna-starter | > netlify dev
fauna-starter | 
fauna-starter | ◈ Netlify Dev ◈
fauna-starter | ◈ Starting Netlify Dev with vue-cli
fauna-starter | Waiting for localhost:3000.
fauna-starter | ◈ Functions server is listening on 34567
fauna-starter | /usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
fauna-starter |       throw ex;
fauna-starter |       ^
fauna-starter | 
fauna-starter | TypeError: dest.end is not a function
fauna-starter |     at ReadStream.onend (_stream_readable.js:679:10)
fauna-starter |     at Object.onceWrapper (events.js:420:28)
fauna-starter |     at ReadStream.emit (events.js:326:22)
fauna-starter |     at endReadableNT (_stream_readable.js:1226:12)
fauna-starter |     at processTicksAndRejections (interna
```
I'm generally following the instructions (using netlify-cli@2.45 for instance), except that I'm running under docker.

I'm not sure where to begin looking for the problem. When searching for the error, I see other people have got it, but the solutions don't seem applicable.

**Comment by paulrosen** [comment]
If I create a shell for the docker image and run "npm start" inside the shell then I don't get that error. I'm not sure what the difference would be from running it directly through docker-compose, but I guess that means the problem isn't in this package.
